import java.security.*;
import java.util.Scanner; 
public class md5
{
   public static void main(String a[]) 
 {
     Scanner myObj = new Scanner(System.in);
      try
      {
	     MessageDigest md = MessageDigest.getInstance("MD5");
	     System.out.println("Message digest object info:");
         System.out.println("Algorithm= " + md.getAlgorithm());
         System.out.println("Provider= " + md.getProvider());
         System.out.println("ToString= " + md.toString());
         byte[] output = md.digest();
         System.out.println("Enter some text: ");
         String ab = myObj.nextLine();
	     md.update(ab.getBytes()); 
         output = md.digest();
         System.out.println("\nYour hash code generated by MD5 is: "+ bytesToHex(output));
          
    } 
   catch (Exception e) 
  { 
    System.out.println("Exception:" + e);
    }
}
private static String bytesToHex(byte[] b)
 {
  char hexDigit[] ={'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'};
  StringBuffer buf = new StringBuffer();
  	for (int j = 0; j < b.length; j++) 
	{
	    buf.append(hexDigit[(b[j] >> 4) & 0x0f]);
	    buf.append(hexDigit[b[j] & 0x0f]);
	  }
	  return buf.toString();
 }
}